name: build and test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # Specify the runner
    runs-on: ubuntu-latest

    # Skip workflow if the commit message contains "[ci skip]"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      # Step: Check out code
      - uses: actions/checkout@v1

      # Step: Verify Angular project compiles
      - name: Verify Angular project compiles
        run: |
          cd terres-de-laya-portal
          npm ci # Install dependencies
          npm run build -- --configuration production # Build the project
